<?xml version="1.0"?>
<!-- Copyright (c) 2016 The UUV Simulator Authors.
     All rights reserved.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<robot name="beluga" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="beluga_base" params="namespace debug inertial_reference_frame">

  <!-- Import xacros -->
  <xacro:include filename="$(find beluga_simulator)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find beluga_simulator)/urdf/sensor_snippets.xacro"/>
  <xacro:include filename="$(find beluga_simulator)/urdf/thruster_snippets.xacro"/>
  
  <!-- Define Parameters -->
  <xacro:property name="mass" value="20"/>
  <xacro:property name="volume" value="0.011054"/>
  <xacro:property name="cog" value="0 0.005 -.03"/>
  <xacro:property name="cob" value="0 0 0"/>
  <xacro:property name="rho" value="1028"/>

  <xacro:property name="x_size" value="0.448"/>
  <xacro:property name="y_size" value="0.2384"/>
  <xacro:property name="z_size" value="0.28066"/>

  <xacro:property name="equivalent_radius" value="${0.5*z_size}"/>
    
  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="${cog}" rpy = "0 0 0"/>
      <inertia ixx="0.26"  iyy="0.40"  izz="0.35"
               ixy="0.001" iyz="0.001" ixz="0.02"/>
    </inertial>
    
    <!-- Main Body -->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.48538 0.27 0.327"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.6 0.47 0.36"/>
      </geometry>
    </collision>

    <!-- Left Front Thruster Mount -->
    <visual>
      <origin xyz="0.27043 0.195 -0.025" rpy="0 0 -${pi}"/>
        <geometry>
          <mesh filename="file://$(find beluga_simulator)/meshes/angled_thruster_mount.dae" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>

    <!-- Right Front Thruster Mount -->
    <visual>
      <origin xyz="0.27043 -0.195 0.025" rpy="${pi} 0 -${pi}"/>
        <geometry>
          <mesh filename="file://$(find beluga_simulator)/meshes/angled_thruster_mount.dae" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>

    <!-- Left Back Thruster Mount -->
    <visual>
      <origin xyz="-0.27043 0.195 0.025" rpy="0 ${pi} -${pi}"/>
        <geometry>
          <mesh filename="file://$(find beluga_simulator)/meshes/angled_thruster_mount.dae" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>

    <!-- Right Back Thruster Mount -->
    <visual>
      <origin xyz="-0.27043 -0.195 -0.025" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://$(find beluga_simulator)/meshes/angled_thruster_mount.dae" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>

    <!-- Left Middle Thruster Mount -->
    <visual>
      <origin xyz="0 0.165 -0.035" rpy="0 0 0"/> 
      <geometry>
        <box size="0.09 0.06 0.05"/>
      </geometry>
    </visual>

    <!-- Right Middle Thruster Mount -->
    <visual>
      <origin xyz="0 -0.165 -0.035" rpy="0 0 0"/> 
      <geometry>
        <box size="0.05 0.06 0.05"/>
      </geometry>
    </visual>

    <!-- Middle Back Thruster Mount -->
    <visual>
      <origin xyz="-0.26769 0 0.1336" rpy="0 0 0"/> 
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>
    
  </link>

  <link name="base_link"/>

  <joint name="${namespace}/dummy_joint" type="fixed">
     <parent link="base_link"/>
     <child link="${namespace}/base_link"/>
  </joint>


    <xacro:include filename="$(find beluga_simulator)/urdf/beluga_thrusters.xacro"/>
    <!-- <xacro:include filename="$(find beluga_simulator)/urdf/beluga_sensors.xacro"/> -->

  </xacro:macro>
</robot>